name: Simulate Running Job

on:
  workflow_dispatch:  # allows manual trigger

jobs:
  wait-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Start
        run: echo "Start job..."
      - name: Wait for 3 minutes
        run: sleep 180
      - name: Print Done
        run: echo "Job complete"
