name: Simulate Running Job

on:
  workflow_dispatch:  # allows manual triggering from GitHub UI

jobs:
  fake-job:
    runs-on: ubuntu-latest
    steps:
      - name: Start Job
        run: echo "Starting a simulated long-running job..."
      - name: Sleep 120 seconds
        run: sleep 120  # sleeps for 2 minutes
      - name: Finish Job
        run: echo "Done."
